spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/users
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Opcional: Ayuda a diferenciar instancias si levantas dos
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka